### PR TITLE
chore: update doublestar to v4

### PR DESCRIPTION
**Pull request by loeffel-io**
It make sense to bump doublestar because `Match` did not changed from `v2` to `v4` [besides big performance improvements](https://github.com/bmatcuk/doublestar/blob/master/UPGRADING.md#upgrading-from-v3-to-v4)

It make sense to merge #1014 before

### CODE REVIEW

**Review by noahdietz — APPROVED** [review]
Great call, thanks!

**Comment by noahdietz** [comment]
@loeffel-io looks like doublstar needs Go 1.16 and uses newer APIs. We will need to update our go.mod before we can take this. After I merge #1014 just update your branch and run `go mod tidy`. Then CI will pass :)

**Comment by loeffel-io** [comment]
@noahdietz 👍 :)

**Comment by noahdietz** [comment]
Ok go ahead and give this another shot with the latest in `main`

**Comment by loeffel-io** [comment]
@noahdietz ✅

**Pull request merged**
