### PR TITLE
Resolved proto file paths.

### PR DESCRIPTION
**Pull request by mingzhi**
It is using `protoparse.ResolveFilenaming` to resolve absolute file paths (e.g., "./test.proto") into relative ones (e.g., "test.proto") before feeding the proto files into `protoparse`.

I verified:
```
git clone git@github.com:googleapis/googleapis.git ~/Downloads/googleapis
api-linter -I ~/Downloads/googleapis --output-format summary $(find ~/Downloads/googleapis -name '*.proto')
```
and got:
```
+--------------------------------------------+------------------+----------------+
|                    RULE                    | TOTAL VIOLATIONS | VIOLATED FILES |
+--------------------------------------------+------------------+----------------+
| core::0131::http-body                      |                1 |              1 |
| core::0131::http-method                    |                1 |              1 |
| core::0151::lro-metadata-type              |                2 |              2 |
| core::0133::http-method                    |                3 |              1 |
| core::0151::lro-types-defined-in-file      |                3 |              1 |
| core::0136::http-method                    |                4 |              4 |
| core::0134::request-message-name           |                5 |              4 |
| core::0133::request-message-name           |                7 |              5 |
| core::0203::input-only                     |                9 |              5 |
| core::0135::response-message-name          |                9 |              6 |
| core::0131::synonyms                       |               11 |              9 |
| core::0136::prepositions                   |               15 |              6 |
| core::0136::http-body                      |               15 |             15 |
| core::0141::count-suffix                   |               17 |             12 |
| core::0151::lro-response-type              |               19 |             13 |
| core::0131::response-message-name          |               20 |             15 |
| core::0133::response-message-name          |               20 |             16 |
| core::0134::response-message-name          |               21 |             14 |
| core::0133::request-resource-field         |               25 |             22 |
| core::0134::request--resource-field        |               26 |             19 |
| core::0140::abbreviations                  |               27 |              9 |
| core::0140::base64                         |               28 |             17 |
| core::0141::forbidden-types                |               29 |             19 |
| core::0135::request-name-field             |               31 |             25 |
| core::0135::http-uri-name                  |               32 |             25 |
| core::0142::time-field-names               |               34 |             27 |
| core::0134::request-mask-field             |               34 |             25 |
| core::0134::http-method                    |               35 |             25 |
| core::0133::request-parent-field           |               39 |             29 |
| core::0158::response-next-page-token-field |               39 |             28 |
| core::0158::request-page-token-field       |               40 |             28 |
| core::0134::http-body                      |               42 |             30 |
| core::0143::standardized-codes             |               43 |             22 |
| core::0158::request-page-size-field        |               46 |             31 |
| core::0203::immutable                      |               49 |             26 |
| core::0136::verb-noun                      |               51 |             24 |
| core::0133::http-body                      |               54 |             38 |
| core::0143::string-type                    |               65 |             40 |
| core::0134::synonyms                       |               65 |             30 |
| core::0134::http-uri-name                  |               66 |             43 |
| core::0135::request-unknown-fields         |               75 |             36 |
| core::0122::camel-case-uris                |               85 |             11 |
| core::0132::request-parent-field           |               87 |             63 |
| core::0151::operation-info                 |              110 |             41 |
| core::0133::request-unknown-fields         |              110 |             45 |
| core::0134::request-unknown-fields         |              157 |             53 |
| core::0133::http-uri-parent                |              176 |            108 |
| core::0142::time-field-type                |              189 |             73 |
| core::0132::request-unknown-fields         |              212 |             79 |
| core::0131::request-name-field             |              241 |            227 |
| core::0131::http-uri-name                  |              257 |            235 |
| core::0140::prepositions                   |              281 |            111 |
| core::0131::request-unknown-fields         |              339 |            248 |
| core::0136::http-uri-suffix                |              391 |            205 |
| core::0203::output-only                    |              820 |            140 |
| core::0192::only-leading-comments          |             1036 |           1036 |
| core::0203::required                       |             1060 |            256 |
| core::0192::has-comments                   |             1182 |            164 |
+--------------------------------------------+------------------+----------------+
Linted 1604 proto files
```

### CODE REVIEW

**Comment by bufdev** [comment]
LGTM

You might want to verify the following cases just to make sure ([bufbuild/buf](https://github.com/bufbuild/buf) has it's own method of path resolution so I haven't used `ResolveFilenames` in a while):

```
api-linter -I . $(pwd)/google/type/date.proto
api-linter -I $(pwd) $(pwd)/google/type/date.proto
api-linter -I $(pwd) google/type/date.proto
api-linter -I $(pwd) ./google/type/date.proto
cd ./google
api-linter -I .. ../google/type/date.proto
```

Would also be good to set up an integration test for this, but you may have this already planned :-)

**Comment by bufdev** [comment]
Note I ran the above, all complete, but #307 still an issue, also the file paths printed are always relative to the `proto_path`, which isn't optimal (but may be out of the scope of this tool):

```
$ api-linter -I . $(pwd)/google/type/date.proto
- file_path: google/type/date.proto
  problems: []
$ api-linter -I $(pwd) $(pwd)/google/type/date.proto
- file_path: google/type/date.proto
  problems: []
$ api-linter -I $(pwd) google/type/date.proto
- file_path: google/type/date.proto
  problems: []
$ api-linter -I $(pwd) ./google/type/date.proto
- file_path: google/type/date.proto
  problems: []
$ cd ./google
$ api-linter -I .. ../google/type/date.proto
- file_path: google/type/date.proto
  problems: []
$ api-linter -I $(pwd)/.. ../google/type/date.proto
- file_path: google/type/date.proto
  problems: []
$ api-linter -I $(pwd)/.. $(pwd)/../google/type/date.proto
- file_path: google/type/date.proto
  problems: []
$ cd ..
$ api-linter $(pwd)/google/type/date.proto
- file_path: google/type/date.proto
  problems: []
```

**Comment by mingzhi** [comment]
> Note I ran the above, all complete, but #307 still an issue, also the file paths printed are always relative to the `proto_path`, which isn't optimal (but may be out of the scope of this tool):
> 
> ```
> $ api-linter -I . $(pwd)/google/type/date.proto
> - file_path: google/type/date.proto
>   problems: []
> $ api-linter -I $(pwd) $(pwd)/google/type/date.proto
> - file_path: google/type/date.proto
>   problems: []
> $ api-linter -I $(pwd) google/type/date.proto
> - file_path: google/type/date.proto
>   problems: []
> $ api-linter -I $(pwd) ./google/type/date.proto
> - file_path: google/type/date.proto
>   problems: []
> $ cd ./google
> $ api-linter -I .. ../google/type/date.proto
> - file_path: google/type/date.proto
>   problems: []
> $ api-linter -I $(pwd)/.. ../google/type/date.proto
> - file_path: google/type/date.proto
>   problems: []
> $ api-linter -I $(pwd)/.. $(pwd)/../google/type/date.proto
> - file_path: google/type/date.proto
>   problems: []
> $ cd ..
> $ api-linter $(pwd)/google/type/date.proto
> - file_path: google/type/date.proto
>   problems: []
> ```

I think it is really hard (or impossible) for the linter to resolve back the absolute paths. The solution could be that we resolve manually the paths in the linter, and keep tracking the mappings. But it is too much for the linter currently. Thank you for bringing it up!!!

**Comment by bufdev** [comment]
It takes some work, but we were able to do it in Buf for the record (and not to sound like a broken record, sorry heh):

```
$ buf check lint
google/appengine/v1/app_yaml.proto:53:5:Enum option "allow_alias" on enum "ErrorCode" must be false.
google/appengine/v1/app_yaml.proto:264:3:Enum option "allow_alias" on enum "SecurityLevel" must be false.
google/cloud/websecurityscanner/v1beta/scan_config_error.proto:35:5:Enum option "allow_alias" on enum "Code" must be false.

$ buf check lint --input $(pwd)
/Users/foo/googleapis/google/appengine/v1/app_yaml.proto:53:5:Enum option "allow_alias" on enum "ErrorCode" must be false.
/Users/foo/googleapis/google/appengine/v1/app_yaml.proto:264:3:Enum option "allow_alias" on enum "SecurityLevel" must be false.
/Users/foo/googleapis/google/cloud/websecurityscanner/v1beta/scan_config_error.proto:35:5:Enum option "allow_alias" on enum "Code" must be false.

$ cd ./google

$ buf check lint --input ..
appengine/v1/app_yaml.proto:53:5:Enum option "allow_alias" on enum "ErrorCode" must be false.
appengine/v1/app_yaml.proto:264:3:Enum option "allow_alias" on enum "SecurityLevel" must be false.
cloud/websecurityscanner/v1beta/scan_config_error.proto:35:5:Enum option "allow_alias" on enum "Code" must be false.

$ buf check lint --input $(pwd)/..
/Users/foo/googleapis/google/appengine/v1/app_yaml.proto:53:5:Enum option "allow_alias" on enum "ErrorCode" must be false.
/Users/foo/googleapis/google/appengine/v1/app_yaml.proto:264:3:Enum option "allow_alias" on enum "SecurityLevel" must be false.
/Users/foo/googleapis/google/cloud/websecurityscanner/v1beta/scan_config_error.proto:35:5:Enum option "allow_alias" on enum "Code" must be false.
```

There may be some stuff you can take from there, but it's complicated as a direct port (Buf uses it's own storage abstraction so direct file I/O isn't common in Buf)

**Comment by lukesneeringer** [comment]
I am going to take the position here that while this likely could be better as @bufdev points out, it seems like an improvement, and so should go in. :)

**Comment by lukesneeringer** [comment]
P. S. Thanks for all your help @bufdev!

**Comment by mingzhi** [comment]
Thank you @bufdev! We will continue to improve integration tests and fix the paths in the output. I am merging this PR as I like PRs to be small :)

**Pull request merged**
