### PR TITLE
feat(AIP-203): add resource name IDENTIFIER enforcement

### PR DESCRIPTION
**Pull request by noahdietz**
Enforces AIP-203 guidance added in https://github.com/aip-dev/google.aip.dev/pull/1201 that the resource's name field must have `google.api.field_behavior = IDENTIFIER`.

### CODE REVIEW

**Review by toumorokoshi — APPROVED** [review]

**Comment by sam-utila** [comment]
This breaks the lint for me.
I have an identifier, but it still fails on linting.

**Comment by noahdietz** [comment]
@sam-utila can you open an issue instead of commenting on the PR? Also please include the proto that is failing.

worth noting this hasn't been released yet so you are using `main` which is probably not advisable.

**Comment by sam-utila** [comment]
No problem, considering I can always put new linting rules on `disabled`.

Just wondering that sometimes `IDENTIFIER`s can also be `OUTPUT_ONLY` and this is something that is now not encouraged by this AIP - haven't sinked in yet :-) .

**Comment by flyfire2002** [comment]
I too am interested in the implication for `name` fields currently marked as `OUTPUT_ONLY`. I guess semantically `IDENTIFIER` doesn't preclude a behavior that is `OUTPUT_ONLY` ("Server ignores it if set as input"). However now we don't have a language for https://google.aip.dev/203#output-only scenario 3 where the name is the immutable field.

**Pull request merged**
