### PR TITLE
Added AIP number in rule register function.

### PR DESCRIPTION
**Pull request by mingzhi**
Rule registering now requires a valid AIP number. It removes the redundant tests in each rule package testing if a rule is in the right group.

### CODE REVIEW

**Comment by mingzhi** [comment]
This PR removes >500 lines of duplicated codes :)

**Comment by lukesneeringer** [comment]
I think this PR would drop coverage in the rule modules below 100%, would it not?

**Comment by mingzhi** [comment]
> I think this PR would drop coverage in the rule modules below 100%, would it not?

I just realized we never try to catch errors when registering a rule (see [this example](https://github.com/googleapis/api-linter/blob/dc122848d11993e27560699426456f313760cc19/rules/aip0122/aip0122.go#L25)). In other words, `AddRules` must returns an error or panic.

**Comment by mingzhi** [comment]
> I think this PR would drop coverage in the rule modules below 100%, would it not?

The coverage is back to 100%. But we need to fix the meta_linter.

**Comment by mingzhi** [comment]
```
ok  	github.com/googleapis/api-linter/rules	0.220s	coverage: 100.0% of statements
ok  	github.com/googleapis/api-linter/rules/aip0122	0.227s	coverage: 100.0% of statements
ok  	github.com/googleapis/api-linter/rules/aip0126	0.254s	coverage: 100.0% of statements
ok  	github.com/googleapis/api-linter/rules/aip0131	0.233s	coverage: 100.0% of statements
ok  	github.com/googleapis/api-linter/rules/aip0132	0.203s	coverage: 100.0% of statements
ok  	github.com/googleapis/api-linter/rules/aip0133	0.316s	coverage: 100.0% of statements
ok  	github.com/googleapis/api-linter/rules/aip0134	0.240s	coverage: 100.0% of statements
ok  	github.com/googleapis/api-linter/rules/aip0135	0.234s	coverage: 100.0% of statements
ok  	github.com/googleapis/api-linter/rules/aip0136	0.257s	coverage: 100.0% of statements
ok  	github.com/googleapis/api-linter/rules/aip0140	0.294s	coverage: 100.0% of statements
ok  	github.com/googleapis/api-linter/rules/aip0141	0.295s	coverage: 100.0% of statements
ok  	github.com/googleapis/api-linter/rules/aip0142	0.301s	coverage: 100.0% of statements
ok  	github.com/googleapis/api-linter/rules/aip0143	0.190s	coverage: 100.0% of statements
ok  	github.com/googleapis/api-linter/rules/aip0151	0.208s	coverage: 100.0% of statements
ok  	github.com/googleapis/api-linter/rules/aip0158	0.209s	coverage: 100.0% of statements
ok  	github.com/googleapis/api-linter/rules/aip0191	0.243s	coverage: 100.0% of statements
ok  	github.com/googleapis/api-linter/rules/aip0192	0.448s	coverage: 100.0% of statements
ok  	github.com/googleapis/api-linter/rules/aip0203	0.315s	coverage: 97.7% of statements
ok  	github.com/googleapis/api-linter/rules/aip0231	0.311s	coverage: 100.0% of statements
ok  	github.com/googleapis/api-linter/rules/internal/data	0.065s	coverage: [no statements]
ok  	github.com/googleapis/api-linter/rules/internal/testutils	0.164s	coverage: 100.0% of statements
ok  	github.com/googleapis/api-linter/rules/internal/utils	0.164s	coverage: 100.0% of statements
```

**Comment by mingzhi** [comment]
> I think that the `AddRules` pattern may have been an error. We can always change it later, but this is an incremental improvement.

+1

**Pull request merged**
