### PR TITLE
Use package-level README.md to describe rules in a package

### PR DESCRIPTION
**Pull request by mingzhi**
Preview: https://github.com/googleapis/api-linter/tree/github_page/rules/aip0203

### CODE REVIEW

**Comment by lukesneeringer** [comment]
Advantages to this approach:

- Markdown support
- Documentation for linter users is separated clearly from documentation for linter contributors.

Disadvantages to this approach:

- Documentation is farther from the code; more likely to go out of date.
- It somehow does not look quite as nice (surprising given that, well, Markdown)

I could accept either of these.

**Comment by jgeewax** [comment]
Can we add a lint rule style guide if we're going to go this way? For example, the *correct* version should probably be before the incorrect one, etc.

**Comment by mingzhi** [comment]
Yes, I think we can create (1) a style guide and example template; (2) a CI to check that each rule must have a description page and the right style.

And I have the same concern about code and markdown being separated (and we need to catch out-of-date issues in code review). But the markdown page is easy to write and highlight some information.

**Comment by lukesneeringer** [comment]
> Can we add a lint rule style guide if we're going to go this way? For example, the _correct_ version should probably be before the incorrect one, etc.

FWIW, that is the opposite of what you did internally.

**Comment by mingzhi** [comment]
In this PR, I basically copy and paste the internal version :)

**Comment by jgeewax** [comment]
> > Can we add a lint rule style guide if we're going to go this way? For example, the _correct_ version should probably be before the incorrect one, etc.
> 
> FWIW, that is the opposite of what you did internally.

Correct -- internally we have red and green colors though -- so the order matters much less. Since we don't have the color coding, we have to be more careful.

**Pull request closed without merging**
