### PR TITLE
Rewrote the linter cmd to offer a simpler interface.

### PR DESCRIPTION
**Pull request by mingzhi**
Usage:

```sh
api-lint proto_file1 proto_file2 ...
```

```
Usage of api-lint:
  -I value
    	The folders to search for proto imports.
  -c string
    	The config file.
  -f string
    	The format of the printed results.
  -o string
    	The output file path.
```

### CODE REVIEW

**Comment by lukesneeringer** [comment]
Let's stick with `api-linter` as the command (not `api-lint`), please.

Can we have a short form and a long form for the switches (e.g. `-c`, `--config`)?

**Comment by mingzhi** [comment]
> Let's stick with `api-linter` as the command (not `api-lint`), please.
> 
> Can we have a short form and a long form for the switches (e.g. `-c`, `--config`)?

In those cases, I will close this PR, but create another one to shorter `api-linter checkproto` to `api-linter check` with an alias `api-linter c`.

**Comment by mingzhi** [comment]
@lukesneeringer, please take another look:
```
Usage of api-linter:
  -config string
    	The linter config file.
  -out_format string
    	The format of the linting results.
  -out_path string
    	The output file path.
  -proto_desc string
    	The file descriptor set for proto imports
  -proto_path value
    	The folder to search for proto imports.
```

I decided not to include the short forms of flags, since it would save little typings but rather increase confusion and memorization.

**Comment by mingzhi** [comment]
```
Usage of api-linter:
  -config string
        The linter config file.
  -output_format string
        The format of the linting results.
        Supported formats include YAML, JSON and summary text.
        YAML is the default.
  -output_path string
        The output file path.
        If not given, the linting results will be printed out to STDOUT.
  -proto_descriptor_set string
        The file descriptor set for searching proto imports.
  -proto_path value
        The folder for searching proto imports.
        May be specified multiple times; directories will be searched in order.
        The current working directory is always used.
```

**Pull request merged**
