### PR TITLE
feat: Add rule for AIP-162 Delete Revision response message name

### LINKED ISSUE #721: Missing rules for AIP-162
https://google.aip.dev/162

# Tag Revision
- [x] HTTP body
- [x] HTTP method
- [x] HTTP URI suffix
- [x] Request message name
- [x] Request `name` field
- [x] Request `name` field behavior
- [x] Request `name` field resource reference
- [x] Request `tag` field
- [x] Request `tag` field behavior
- [x] Response message name

# List Revisions
- [x] HTTP body
- [x] HTTP method
- [x] HTTP URI suffix
- [x] Request message name
- [x] Request `name` field
- [x] Request `name` field behavior
- [x] Request `name` field resource reference
- [x] Request should not have an `order_by` field
- [x] Response message name

# Commit Revision
- [x] HTTP body
- [x] HTTP method
- [x] HTTP URI suffix
- [x] Request message name
- [x] Request `name` field
- [x] Request `name` field behavior
- [x] Request `name` field resource reference
- [x] Response message name

# Rollback
- [x] HTTP body
- [x] HTTP method
- [x] HTTP URI suffix
- [x] Request message name
- [x] Request `name` field
- [x] Request `name` field behavior
- [x] Request `name` field resource reference
- [x] Request `revision_id` field
- [x] Request `revision_id` field behavior
- [x] Response message name

# Delete Revision
- [x] HTTP body
- [x] HTTP method
- [x] HTTP URI suffix
- [x] Request message name
- [x] Request `name` field
- [x] Request `name` field behavior
- [x] Request `name` field resource reference
- [ ] Response message name

### PR DESCRIPTION
**Pull request by apasel422**
Fixes #721.

### CODE REVIEW

**Comment by apasel422** [comment]
See my comment at https://github.com/googleapis/api-linter/issues/721#issuecomment-810272642 before approving this.

**Review by lukesneeringer — APPROVED** [review]

**Review by lukesneeringer — CHANGES_REQUESTED** [review]
I assert that DeleteRevision should return the resource.

**Comment by apasel422** [comment]
> I assert that DeleteRevision should return the resource.

Always, or just for resources supporting soft-delete?

**Comment by lukesneeringer** [comment]
Always.

**Comment by apasel422** [comment]
In that case we need to update https://google.aip.dev/162#deleting-revisions first.

**Comment by apasel422** [comment]
> In that case we need to update https://google.aip.dev/162#deleting-revisions first.

https://github.com/aip-dev/google.aip.dev/pull/741

**Comment by apasel422** [comment]
Ping.

**Review by lukesneeringer — APPROVED** [review]

**Pull request merged**
