### PR TITLE
fix: Render URIs in github actions links

### PR DESCRIPTION
**Pull request by achew22**
Include linter rule URI in findings for GitHub Action format.

### CODE REVIEW

**Comment by noahdietz** [comment]
Need to rebase/update this branch since I just merged the other one with the Location span handling logic.

**Comment by GregFurmanek** [comment]
Any chance your initial description would highlight what is this CL supposed to do/fix/accomplish? It helps to understand intent behind the change.

**Comment by achew22** [comment]
@noahdietz rebased

**Review by noahdietz — APPROVED** [review]

**Comment by noahdietz** [comment]
> Any chance your initial description would highlight what is this CL supposed to do/fix/accomplish? It helps to understand intent behind the change.

Good idea, I added a description :)

**Pull request merged**
